server:
  port: 9110
spring:
  application:
    name: registration-service
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: localhost
  password: ${EUREKA_USER_PASSWORD:password}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
